### ISSUE TITLE
Tweaking this theme

### ISSUE THREAD

**Issue by clausbertels** [Zonnev/elementaryos-firefox-theme#100]
Hi. Thank you **so** much for this! I dislike FF's default tabs on top. There's no room to drag the window even with that option "drag space" selected. This theme is simply brilliant.

## Issue

I tried to delve into the stylesheet, but my god, it's huge. Is there any way you could add some variables at the top that we could tweak? 

I'm personally looking for some more padding above and below the site title in the tabs, and above and below the text in the url box. And to hide the tiny rounded corners on the top of active tabs.

**Comment by Zonnev** [comment]
Hi, thanks for your compliments!

I'm not going to use variables any time soon since I'm now well familiar with the style sheet and feel the need to solve issues at places in the style sheet where it's needed. I'm aware it's not easy to adjust for others when they need to figure out where things are. In the Odin version of the theme I have made more section-headers to see what styles are for which part of the theme. For variables I need to do lot's of more work, even rewrite the whole theme.

Padding for the site titles in the tabs you can find at `.tab-content:not([pinned])`, `.tab-content:not([pinned]):not([selected="true"])`, `.tab-content[pinned]` and `.tab-content[pinned]:not([selected="true"])`. These all have a `padding-bottom` which can be adjusted. Be sure to have the same values for all of them if you don't want a change in the position when you select an unfocused tab.

Above and below padding to the text in the url bar I haven't styled but perhaps you can add the padding to `#urlbar-input`. Again, I have not specified this selector, so you have to add it in the stylesheet. Add `padding-top` and/or `padding-bottom` values to `#urlbar-input`.

The rounded corners of the tabs you can adjust at `.tabbrowser-tab[selected="true"]`. This selector has `border-top-left-radius: 4px !important;` and `border-top-right-radius: 4px !important;`. You can put them to `0px` or maybe delete the whole selector as I think it will turn to default, which is squared corners.

Hope to have helped you out!

**Comment by clausbertels** [comment]
Thanks, that did help me out a little. Something interesting though: I can only get rid of the tab corners by setting the radii in `.tab-background[selected="true"]` To 0px. Setting the one you suggested made no difference. 

Another issue is that adding padding won't change the tab height. Where can I find that one?

**Comment by Zonnev** [comment]
Oops, the rounded corners are also in selector: `.tab-background[selected="true"]`.. sorry, I forgot about it. I styled tab-background, not tabbrowser-tab. 

The height of the tabs are made by two selectors. The tab needs to fit the `#TabsToolbar`, which is the toolbar where the tab is in. And the tab has a minimum height. In  `#TabsToolbar` the height is 31px and the min-height is specified in: 
```
:root {
    --tab-min-height: 30px !important; /* adjust to suit your needs */ 
}
```
You can find them around line 950. Hope you see them, good luck!

Btw, if you change these selectors, and you want to switch to the dark mode or private mode and don't see change, you will need to find the exact same selector for these modes.

Dark mode has two sections: dark mode for tweaks and dark mode standalone. Dark mode for tweaks starts first in the stylesheet around line 1233. Dark mode standalone starts after it around line 1483. Dark mode standalone has `:-moz-lwtheme-brighttext` behind every selector. Private mode is last in the stylesheet and has `#main-window[privatebrowsingmode="temporary"] ` before every selector.

I hope you can find the matching selectors in the other modes.

**Comment by clausbertels** [comment]
Thanks! With your help I have it almost perfect.

![Schermafdruk van 2020-12-28 19 59 33](https://user-images.githubusercontent.com/25482509/103237235-455a8d00-4947-11eb-8edf-c695c5399975.png)

**Comment by clausbertels** [comment]
Maybe one last thing: where can I find the box-shadow for the navigation panel? Or is that an inner shadow of the background tabs?

**Comment by Zonnev** [comment]
You are right, it's the inset box-shadow in `#TabsToolbar`.

**Comment by Niko-Berd** [comment]
Did not want to make a different topic so I guess it's better to continue in current thread. Is there a way to make back,forward & refresh buttons smaller? They're way too big compared to everything else even with 'compact' density. Thanks.
![Screenshot from 2020-12-29 17 51 20](https://user-images.githubusercontent.com/40539342/103288587-9f6a5980-49fe-11eb-9da3-d154b6c953aa.png)

**Comment by Zonnev** [comment]
@Niko-Berd look up this section in the style sheet:
```
/* keep default icons small while below icons are bigger */
#back-button > .toolbarbutton-icon,
#forward-button .toolbarbutton-icon,
#reload-button .toolbarbutton-icon,
#stop-button .toolbarbutton-icon,
#home-button .toolbarbutton-icon {
    padding: 2px !important;
    clip-path: circle(50%) !important;
}
```
A higher value of the padding will make the buttons smaller. Don't go too high, you can probably set it to 3px, which makes them quite a bit smaller already. You can also play with tens of the value, like 2.5px.

**Comment by Zonnev** [comment]
I close this issue because all questions are answered. Create a new issue if you have more questions.
