### ISSUE TITLE
Option to override default theme

### ISSUE THREAD

**Issue by tonilampela** [Zonnev/elementaryos-firefox-theme#101]
This is not the highest priority request, but it would be great to have an option to override default themes - e.g. set the lovely purple team to be the default instead seeing it only in private browsing mode.

**Comment by Zonnev** [comment]
This would involve making a new userChrome.css file. I then would make a new repository on Github for it. I think I won't be doing this anytime soon since I have the Odin theme and the Hera to maintain. Maintaining 2 theme's is enough for me in my spare time ;) Maybe when the Hera theme falls off when everybody using Odin anyways, then I could work on this request.

**Comment by Zonnev** [comment]
I closed this issue since it involves making a new theme which I'm not going to do, also not in the future.
