### ISSUE TITLE
Auto-hide tab bar

### ISSUE THREAD

**Issue by kdwk** [Zonnev/elementaryos-firefox-theme#103]
Can you please add an option to hide the tab bar when the current tab is the only tab open in the window?

Like this: https://github.com/rafaelmardojai/firefox-gnome-theme     Readme.md-> Features-> Hide single tab bar

**Comment by Zonnev** [comment]
I can only hide the active tab, but not the whole tab bar. I tried with this:
```
/* OPTIONAL: Hide tabbar */
@supports -moz-bool-pref("elementaryos-firefox-theme.hide-tabbar") {
	#TabsToolbar tab:only-of-type {
		display: none !important;
	}
}
```
But it doesn't work hiding the whole tab bar, so I guess I'm doing something wrong since I don't know exactly how it works. I know I should keep `tab:only-of-type`, so I did put the tab bar selector before it: `#TabsToolbar` and hoped it would hide it, but it doesn't. Maybe someone else can help us with this.

**Comment by arkraft** [comment]
I use this for a while now: 
```

/* Hide solo tab */
#tabbrowser-tabs tab[first-visible-tab="true"][last-visible-tab="true"] {
  visibility: collapse;
}
/* Hide New Tab Button immediately next to solo tab */
#tabbrowser-tabs tab[first-visible-tab="true"][last-visible-tab="true"] + toolbarbutton {
  visibility: collapse;
}

.tabbrowser-tab {
  margin-bottom: -1px !important;
}
```

I looks like this: 

![grafik](https://user-images.githubusercontent.com/7426376/103937930-cbd25400-5129-11eb-8848-e80fa5acd7b9.png)

Two things are not working though.
 1. There is no "new Tab" button anymore if there is only one tab. It would be in the tab bar so the tab bar would be visible, so i hide it when there is only one tab
 2. There is a second border which i tried to hide but all results looked shit, so this is currently the best i came up with. Haven't tried in a while though. Maybe i should give it another shot

**Comment by Zonnev** [comment]
@arkraft Your CSS doesn't (auto)hide the tab bar, which I asked for. But thanks anyways for showing another way to hide the first tab.

**Comment by arkraft** [comment]
> Can you please add an option to hide the tab bar when the current tab is the only tab open in the window?

It does exactly this. If a second tab is opened, the tab bar appears. If you only have one, it is not visible. What exactly does autohide mean here?

**Comment by Zonnev** [comment]
`#tabbrowser-tabs` is the selector for tabs in the tab browser, not the selector for the tab bar (`#TabsToolbar`). So, essentially yes, you are hiding the first tab and make it appear when the last tab is opened and active, but the CSS is **not** hiding the tab bar and make the tab bar appear (automatically) when the last tab is opened.

Also by adding `toolbarbutton`, it is only selecting the new tab button in one position. So, the visibility of the new tab button (the actual selector when its placed to the left of the tabs is: `#new-tab-button`) is **not** being collapsed in my Firefox setup - it is still visible when I add your code because I placed it to the left of the tabs.

But the above is not a big problem to adjust, but sadly, the tab bar still remains visible (using your CSS) with one tab open. I don't know how to solve this... :(

**Comment by Zonnev** [comment]
I'm not able to add this to the theme, so I close this issue.
