### ISSUE TITLE
"Add to the Address Bar" menu entry flashes when the mouse cursor moves over it.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#116]
1- Go to a website.
2- Press the three dots on the address bar and right click on any of the icons.
3- Move mouse cursor over the "Add to the Address Bar" option.

**Result:** The menu entry flashes when the mouse cursor moves over it.

Note: I don't know if this is worth fixing it because apparently Proton will remove the ability to add this icons to the address bar.

**Comment by Zonnev** [comment]
You are right, it does flashes but I can't solve this quickly. I think it has something to do with the menu of the 3 dots itself. This menu is yet another menu which needs to have `:hover` styling. I think if I fix that, the menu will run more smoothly but since it's not an easy fix and soon the menu won't be in use anymore, I won't fix this. Thanks anyway for discovering it!
