### ISSUE TITLE
[Proton] The Reader Mode and Bookmark address bar icons are abnormally small.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#119]
The Reader Mode and The Bookmarks star on the address bar seem to be too small. It's possible that other icons are affected, but from now I'm only seeing this ones.

**Comment by Zonnev** [comment]
This is what I adjusted so far:
![Schermafdruk van 2021-06-04 17 59 28](https://user-images.githubusercontent.com/32688765/120830371-b63d4b00-c55e-11eb-90d7-af907b63f827.png)
Turned out the zoom function wasn't readable and all the icons were too small, like you've mentioned. If you come across some more problems with these icon's, you can mentioned those issues here. Thanks!

**Comment by Blast-City** [comment]
Hi.

The reader mode icon issue is back. Can you check it out?

Thanks.

**Comment by Zonnev** [comment]
Oops, I forgot to write that this issue is solved... 7 hours ago...

**Comment by Blast-City** [comment]
Fixed.

Thanks.
