### ISSUE TITLE
Popup menu problem flickering hover effect

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#129]
1- Open the Application Menu and click on History.
2- Right click on a history item and move the mouse.

Result: Moving the mouse highlights both what is beneath and on the context menu resulting in a flash effect. This seems related to #116

Thanks.

**Comment by Zonnev** [comment]
This popup menu that shows up and the popup menu from History are both menu's that I adjusted with css. I think my css is conflicting with the default css when opening menu's on top of each other. To solve this is to turn off my css for these menu's otherwise I wouldn't know what to do about it. I began my own experiment styling these menu's in every part of Firefox and I like what the css does, but when two menu's are on top of each other, it does weird flashy things just like what happened with issue #116. I guess my experiment is not 'bullet proof'... Knowing this all, I think we should avoid opening menu's on top of each other, not because the menu's won't work, because they do work but they show flaws.

**Comment by Zonnev** [comment]
I have figured out what happens: The flashes are: default css (dark grey selection) and new css (lighter grey selection) being both selected by mouse hovering it. This is because the background of the new styled menu's are in fact made transparent to accomplish rounded corners. Without the css with the transparency and the mask that goes over it, there was no way to make menu's with rounded corners...

**Comment by Blast-City** [comment]
Thanks for the detailed explanation. I would say that it's be better to sacrifice the round corners if this happened frequently, but as much as I can see it only happens in that situation.

Should I close it?

**Comment by Zonnev** [comment]
I leave this issue open and I changed the title to be more direct. If you come across more problems and issues with this effect I will be glad to read them here. Thank you :)

**Comment by Zonnev** [comment]
I think the flickering effect is gone since shadows has been removed. Can you verify that? Thanks.

**Comment by Zonnev** [comment]
Oops this issue belongs to the elementary 5 theme where it's still present I guess.

**Comment by Blast-City** [comment]
Hi.

I haven't installed Odin yet, but I will close it to keep the issues page cleaner. I'll reopen it if I notice anything wrong.

Thanks.
