### ISSUE TITLE
Container tabs are not highlighted

### ISSUE THREAD

**Issue by tokkoz** [Zonnev/elementaryos-firefox-theme#132]
Container tabs are not highlighted after proton update. Colored line on tab is missing so now the only container indication is in url bar. Used to work before proton.

without css
![wihtout css](https://user-images.githubusercontent.com/69058848/125506478-0794e1ab-203f-41a2-838b-7c7cbbe91a7a.png)

with css
![with css](https://user-images.githubusercontent.com/69058848/125506495-6269e9aa-a4d4-4b96-bdeb-63fd51d41a5c.png)

**Comment by Zonnev** [comment]
Hmm, you're right... the highlighted line on the active tabs is probably not present anymore in Proton. I didn't noticed this before because my theme doesn't show the tab line on purpose, it has `display: none`. But when I remove this line from userChrome, the tab line doesn't show and when I use Firefox without my userChrome, it doesn't show the line either. So I guess Proton is without the tab line although I saw images of Proton with the tab line weird enough on an inactive tab!... 

So, my question is: do you know when Firefox Proton, without css, shows the tab line and is it only on active tab or also inactive?

**Comment by tokkoz** [comment]
All tabs should be highlighted, active and inactive.
![Screenshot from 2021-07-13 22 42 23](https://user-images.githubusercontent.com/69058848/125523960-462739ca-3592-4f15-a65c-296fa0570f96.png)

Did some digging and found why the highlighted line doesn't show. It has negative margin which makes it hide behind navbar so just changing the margin should fix the issue.
```
.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {
    background-color: var(--identity-icon-color);
    height: 2px;
    border-radius: 2px;
    margin: -3px 2px 0;
}
```
This is with 0 top margin.
![image](https://user-images.githubusercontent.com/69058848/125524871-d3aebda5-c064-4d0a-91f5-30a2ac6f8eed.png)

Hope this helps.

**Comment by Zonnev** [comment]
I find it weird that my Firefox does not show a highlighted line above the tabs. Also when I look at the code inside Firefox (with Browser Tools) and select ` class="tab-context-line"` it does not show the css values like you showed me, in fact it has no values!

I'm wondering if it's some `about:config` setting I need to turn on? Or maybe I have a wrong version of Firefox? Do I need the flathub version?

**Comment by tokkoz** [comment]
I use repo (stable) version and only change in about:config is turning on legacy style sheet.

Maybe creating new profile with fresh config and freshly installed Container extension would work?

**Comment by Zonnev** [comment]
Ah now I understand, you have an extension installed. I can not adjust my theme for extensions people install in Firefox, I'm sorry... You have to adjust the userChrome yourself for this issue to take effect. Good luck!

**Comment by tokkoz** [comment]
Even if it is addon made and supported by Mozilla?

https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by Zonnev** [comment]
My theme is made for standard Firefox on elementary OS. The only thing I adjusted which is not standard is the dark theme for elementary Tweaks since lots of people use this to actually make the dark theme work in eOS Hera. I'm not going to put more css in for all the extensions people use or not use (revert css), I'm sorry...

**Comment by tokkoz** [comment]
I understand your point of view. Thanks for the effort.
