### ISSUE TITLE
Turn off gigantism in the dropdown menu of the address bar

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos-firefox-theme#133]
I tried the new Odin theme and I have to say that it is awesome! I think this gigantism only ruins the look!
![Ekrankopita je 2021-08-02 18 34 03](https://user-images.githubusercontent.com/72291366/127857224-873f4988-81c2-4dbd-b527-fadde3ab2544.png)

**Comment by Zonnev** [comment]
Hello, I've made the bars you mentioned a bit smaller. These changes are only a few pixels because I don't find the bars too big and if I would make these bars really small it would involve making the icons smaller too, which means more css... I hope you like the small changes, you can install the new userChrome and thank you for the compliments :)
