### ISSUE TITLE
The menu is no longer rounded

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos-firefox-theme#138]
Gone are the roundnesses in the mouse menu and bookmarks. It looks like this:
![Ekrankopita je 2021-08-13 19 19 34](https://user-images.githubusercontent.com/72291366/129356443-54b07855-a18f-4667-831c-5680a3fd7f0e.png)
By the way, I noticed that the windows have it too. Here is window, its sharp left edge is visible, though poorly.
![Ekrankopita je 2021-08-13 19 21 09](https://user-images.githubusercontent.com/72291366/129356799-6ebbf379-b896-4cbf-a615-27a1c4a7e1e6.png)
But the edge of the private window is more striking. 
![Ekrankopita je 2021-08-13 19 20 31](https://user-images.githubusercontent.com/72291366/129356833-7c036d97-2bc9-4aa9-90e4-2514b3228bc0.png)
Is it possible to fix it?

**Comment by Zonnev** [comment]
Hi, I don't see it. Here at my side all menu's have rounded corners. Maybe you have an extension running in Firefox that causes problems? 

For the crooked rounded window corners; I will try to solve that issue.

**Comment by Zbergen-cli** [comment]
Hmm, disabling the extensions and a new profile doesn't give any results...

UDP

I checked it on the arch and here there is no this problem with the menu...

**Comment by Zonnev** [comment]
I guess, if you are on a clean install of eOS Odin, like I am, you shouldn't have this problem with the menu's either. I'm sorry but I probably can not solve it since I can not reproduce this issue on my computer.

The crooked window corners I can not solve either. Default Firefox doesn't even show the corners at all, although they made the main window transparent, ready for rounded corners. I think Firefox still adres the old GTK rounded corners of eOS Hera, that why we see the white bit around the corners. I don't think Firefox devs will introduce CSS specially for eOS Odin...

**Comment by Zonnev** [comment]
The white bits only show on light parts of your screen, so you can solve the window corner problem a bit by using a dark even background.
