### ISSUE TITLE
Styling main menu and bookmark menu

### ISSUE THREAD

**Issue by kepebi** [Zonnev/elementaryos-firefox-theme#140]
Hey. I think it is worth bringing the main menu and the bookmark menu to a common view.

**Comment by Zonnev** [comment]
Hi, I would be glad to help but I don't understand what you mean by a common view. Can you explain? Thanks.

**Comment by kepebi** [comment]
For example, let's see what a mouse menu looks like:

![Menu](https://user-images.githubusercontent.com/88997820/129549436-6807d7cd-4b70-470e-8058-cf37c070c94a.png)

Elements of normal size, no padding, no rounding on hover. Generally cool! And here is the bookmark menu:

![Menu 2](https://user-images.githubusercontent.com/88997820/129549501-30200587-bf95-40d0-95a4-661aa490565e.png)

Large elements, extra padding on all sides, rounding on hover ...

I would like the bookmark menu and main menu to look similar to the mouse menu :)

**Comment by Zonnev** [comment]
I've made the menu's more like the right mouse click menu. Thanks for posting this issue :) You can install the new userChrome.

**Comment by kepebi** [comment]
Much better!

Take a look at the padding in the submenu... 

![Menu2](https://user-images.githubusercontent.com/88997820/129570375-b027e680-dd1c-49d2-b3fc-de8c4649c905.png)


don't you think they add volume? Maybe you should completely delete them in the submenu, in the bookmarks menu and in the main menu? If you don’t want to, maybe it’s better to set the same size for all indents?

**Comment by Zonnev** [comment]
This is only the bookmarks popup menu. I adjusted some rules about padding of menus globally, it was the easy way so the indents are the same size in all arrow panel menu's. The indents of the bookmarks menu should be smaller though to make it look the folder icons are before the indents. But sorry, I will not work on that since it's such a lot of work for such a minor change. Hope you can live with how it is now :)

**Comment by kepebi** [comment]
I understand :) Thanks for that too.
