### ISSUE TITLE
Invisible titlebar buttons

### ISSUE THREAD

**Issue by tashimotor** [Zonnev/elementaryos-firefox-theme#152]
![изображение](https://user-images.githubusercontent.com/14804351/142049405-69fd023b-8ffa-4c2a-8ff8-f2b3870e29b0.png)

I've done full install with instructions from readme. But every setting of titlebar position is only about empty space for buttons. Buttons are not there.

Fedora 35 with Pantheon
Firefox 94

**Comment by Zonnev** [comment]
I'm not sure but maybe this is because I did hide "double" window buttons in the userChrome. In native elementary OS there is no use for double window buttons and it created issue #145. 

Please search for `#TabsToolbar .titlebar-buttonbox-container { display: none !important; }` in the userChrome and remove that line. In the default layout (option 1 in the installer) it is line 193 in the userChrome. I hope removing it solves your issue.

**Comment by Zonnev** [comment]
There is no reply to my possible solution for awhile. I close this for now but we can reopen it when you need.
