### ISSUE TITLE
Tabs above bookmarks

### ISSUE THREAD

**Issue by cipricus** [Zonnev/elementaryos-firefox-theme#153]
If bookmarks are set  to show only on new tabs, the tabs go down when a new tab is opened, and bookmarks jump under the mouse point. That is unexpected, very counterintuitive; simply put: cannot quickly click twice the new tab button, because the second time the button is not under the mouse anymore.

The bookmarks being the variable aspect, they should show/hide without altering/moving the tabs position.

**Comment by Zonnev** [comment]
Thanks for posting this issue! I have changed it: bookmarks and menu bars are now under the tabs bar in the latest userChrome. The work flow is indeed better having it this way.

**Comment by queeup** [comment]
Hey @Zonnev, sorry for saying this but the work flow with bookmarks under the tabs bar is not good for if bookmarks are set to always show. This way clicking tabs is difficult. Sometimes I accidentality clicking bookmarks. I regret that I updated to the latest version...

**Comment by Zonnev** [comment]
Ofcourse now it looks different, the tabs arent the lowest bar anymore and I can see that you by accident click on it, but it's a matter of getting used to, I think.

I prefer to set the bookmarks bar below the tabs so the tabs won't move downwards when the bookmarks bar appears. I think a moving tab bar is worse to click on than when it stays where it is. Since the default behaviour of Firefox is that the bookmarks bar appears on a new tab, the tab bar shouldn't move when clicking on the + button when you are on another website page.
