### ISSUE TITLE
Square borders on OSX layout

### ISSUE THREAD

**Issue by zJairO** [Zonnev/elementaryos-firefox-theme#160]
Good morning, as the title says, I don't know if this is a bug, also the settings button is really on right side, I think it needs a little bit of margin on right.

![](https://i.imgur.com/qNnUt46.png)

Regards and thank you for this beautiful theme.

**Comment by Zonnev** [comment]
Not sure what you mean by borders but it's known that Firefox 95 and 96 have square window corners. This is solved in Firefox 97 which will become stable this month.

I have changed the position of the settings button more to the left, thanks for noticing that issue! You can install the new userChrome. Notice that in the new installer you need to select macOS instead of OSX.

**Comment by zJairO** [comment]
> Not sure what you mean by borders but it's known that Firefox 95 and 96 have square window corners. This is solved in Firefox 97 which will become stable this month.
> 
> I have changed the position of the settings button more to the left, thanks for noticing that issue! You can install the new userChrome. Notice that in the new installer you need to select macOS instead of OSX.

I understand, thank you for fixing the macOS layout, I really appreciate your time.
