### ISSUE TITLE
Strange alignment in the drop-down menu

### ISSUE THREAD

**Issue by ded-ared** [Zonnev/elementaryos-firefox-theme#163]
Hello!
I'm not sure if it's an issue or it's supposed to look this way (or maybe it's just my strange case).
Well, this is the screenshot of the drop-down menu look (bookmark menu, for I use it often) in standard Firefox theme:

![image](https://user-images.githubusercontent.com/58567667/153923397-29517649-546d-4051-9951-c27d1b215903.png)

And this is the drop-down menu in ElementaryOS-theme:

![image](https://user-images.githubusercontent.com/58567667/153923468-820a6b55-07c2-4255-a59a-aee11be4e1fb.png)

In comparison with the standard theme there's a wider gap from the left between menu items and the edge, between item lines (less critical) and something is definitely wrong with alignment.
As for the wide gap on the left it can be observed in other drop-downs as well.

![image](https://user-images.githubusercontent.com/58567667/153923525-8df5ae00-c0b5-4a29-87af-a94e1b4f0080.png)
![image](https://user-images.githubusercontent.com/58567667/153923599-c74a0ad7-1068-44a5-9866-96b9418c2a9c.png)

Is there a way to make drop-downs look as neat as in standard theme?
It has absolutely no impact on functionality, it just looks not very nice.
Firefox is installed via "sudo apt install", updated to the last stable version 97 (but the drop-downs looked that way in all previous versions).

**Comment by Zonnev** [comment]
Thanks for posting this issue. I've made the left margin look alike elementary OS margins in their right click menu's, only the bookmarks dropdown menu behaves differently and need more styling. I was already aware of that but didn't find the time to do something about it. I will soon work on it!

**Comment by ded-ared** [comment]
> I've made the left margin look alike elementary OS margins in their right click menu's, only the bookmarks dropdown menu behaves differently and need more styling.

Aha, so this is the reason of such margin choice. Well, that's ok. Thanks for the explanation and your great work!

**Comment by Zonnev** [comment]
I have aligned the bookmarks menu panel items and main menu panel as well but still the left margin is like the same elementary OS margin. Hope you like it better now. You can install the new userChrome to check it out.

**Comment by ded-ared** [comment]
Oh, sure the bookmarks menu is better! Thanks. Looks more symmetrical now. I guess the items without folder icons are just more difficult to align.

![изображение](https://user-images.githubusercontent.com/58567667/153942494-d4026cd1-411e-495e-8ce7-20ec75becc78.png)

By the way, could you tell which parameters are responsible for alignment (for Preferences drop-down either)? Maybe I'd try to experiment.

**Comment by Zonnev** [comment]
For all panels (the dropdown menus in the toolbar) is `--arrowpanel-menuitem-padding: 7px 12px 7px 27px !important;` applicable. 27px is the left padding, 12px the right padding and 7px is top and bottom padding.

`#BMB_bookmarksPopup .menu-iconic-left { margin-left: -7px !important; }` is addressing the bookmarks panel menu and all left icons in it. I applied -7px margin to align them with the non icon items.

Since I addressed only the bookmarks panel, other menu icons in other menu's won't move, so you need to specify the icons in the Preferences panel. To discover the names of elements in the Preferences panel you need to use the Browser Toolbox. 

https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox is where you can read how to enable the Browser Toolbox. In the Browser Toolbox use the tool on the far left to target an element in the browser and it will show you the name of it. Of course a little knowledge of CSS comes in handy. Anyway, good luck! :)

**Comment by ded-ared** [comment]
I'm aware of just the very basics, but studying always goes better when one's interested and motivated :)
Thanks a lot for the info. Tomorrow is going to be interesting.
