### ISSUE TITLE
MacOS layout, no buttons present when title bar is disabled

### ISSUE THREAD

**Issue by DeeeeLAN** [Zonnev/elementaryos-firefox-theme#184]
The buttons show up properly when the title bar is enabled, but they are nowhere to be found when it is disabled. 

Title bar:
![image](https://user-images.githubusercontent.com/12877032/179393404-3c75115a-58ed-4a7a-84ab-9e7b42cd90dc.png)

No title bar:
![image](https://user-images.githubusercontent.com/12877032/179393678-704736df-bcd1-4834-968a-2230f76dae89.png)

**Comment by Zonnev** [comment]
Hello, I can not reproduce this issue. The titlebar should be disabled and macos should be selected in Tweaks, then you install the theme. Maybe you have installed the Titelbar Enabled version of the theme which will enable the titlebar and disables the other window control buttons.

**Comment by DeeeeLAN** [comment]
That was my original setup. I assume it is an issue with being on Arch running Pantheon instead of Elementary OS. I will dig into it further and let you know.

**Comment by sempasha** [comment]
@DeeeeLAN may your issue be related with #185 ? Please, try to run theme installation again and let us know the result.

**Comment by Zonnev** [comment]
I think this is not an issue with the Titlebar Enabled theme because that theme removes the space for the window control buttons. Seeing the screenshots, the space for the buttons are there but they are empty. 

I think this issue is indeed related with eOS not being native on the pc of @DeeeeLAN and therefore not showing the buttons. I've put the window control buttons display to none in `base.css` (line 254), this is why they are not showing in Arch but are only showing in native eOS.

I think if you want to use Arch and see the buttons, you need to remove at line 254 in `base.css`:
```
#window-controls {
    display: none !important;
}
```
Good luck @DeeeeLAN!

**Comment by DeeeeLAN** [comment]
Thanks for the suggestion. I tried commenting that region and restarting firefox but it didn't appear to make a difference. Something else must be hiding the window controls too.

**Comment by Zonnev** [comment]
Maybe at line 274 you can try commenting this one too:
```
#TabsToolbar .titlebar-buttonbox-container {
    display: none !important;
}
```

**Comment by Zonnev** [comment]
I close this since it seems an inactive issue.
