### ISSUE TITLE
Close buttons broken

### ISSUE THREAD

**Issue by rasmus91** [Zonnev/elementaryos-firefox-theme#202]
I am using the flatpak version of FF, and running this marvelous theme/customization, but recently it broke!

![image](https://github.com/Zonnev/elementaryos-firefox-theme/assets/2297739/d765a44b-6b1f-413c-bdd1-8ffdf4de33ed)
![image](https://github.com/Zonnev/elementaryos-firefox-theme/assets/2297739/7db77a5a-6017-4bfe-9284-7836fe6506c0)

I can't really get a screenshot of it, but when I hover them they turn red for the close button and grey for the maximise. otherwise they are just not there.

**Comment by Zonnev** [comment]
Hi, strange that I don't have this problem. I'm running Firefox 126 flatpak version. Are you sure you installed this theme with the script and not manually? Because the flatpak version needs `flatpak.css`, `base.css` and `userChrome.css` from the right folder, to work properly. 

Otherwise I would start all over again by reinstalling the flatpak version of Firefox and after that install this theme again. If that doesn't work, then  I have no clue what could be wrong...

**Comment by rasmus91** [comment]
This was only resolved after removing the entire thing, reinstalling and then toggling the client side titlebar on and then off again. No clue what's wrong but it's fine now.

Sorry!
