### ISSUE TITLE
Theme is not being applied

### ISSUE THREAD

**Issue by pedrofleck** [Zonnev/elementaryos-firefox-theme#33]
I followed the instructions but the theme isn't applied, I tried downloading the zip and also the latest "release". What am I doing wrong?

**Comment by Zonnev** [comment]
Did you paste the useChrome.css from the zip file in the 'chrome' folder that you created in the profile directory of firefox?

**Comment by pedrofleck** [comment]
Yes, I did.

**Comment by Zonnev** [comment]
Then I don't know... Best to start again with a clean install of firefox or disable all your addon's and see what happens. I've read about a prefs.js file that blocks some functions of the browser including userChrome. Maybe that's what's doing the harm?

**Comment by pedrofleck** [comment]
Actually it was a new install of Firefox 69 from the repo. I was using Chrome and installed Firefox for the first time on this eOS installation just to see this theme.

**Comment by pedrofleck** [comment]
Is there any way to debug what can be happening?

**Comment by Zonnev** [comment]
I have found the cause. Firefox 69 doesn't support userChrome by standard anymore. Here is what you have to do:     
1. Load about:config in the Firefox address bar.
2. Confirm that you will be careful.
3. Search for toolkit.legacyUserProfileCustomizations.stylesheets using the search at the top.
4. Toggle the preference. True means Firefox supports the CSS files, False that it ignores them.
I will add it in the install guide. Good luck!

**Comment by pedrofleck** [comment]
It worked, thanks! And it's looking great, time to go back to Firefox. Any idea why Firefox dropped it? Is there any performance or security issue?

**Comment by Zonnev** [comment]
I actually have no idea why they dropped it. There are no performance issues that I know of, using this theme. There is a change when calling browser.xul which might have something to do with security and performance, but I don't use it in the userChrome provided. Anyway, firefox is gradually changing to html instead of their previous xul, to simplify the code. I hope that would be all they're doing and that they won't totally remove the userChrome access...
