### ISSUE TITLE
No longer fits elementary os defualt dark css color scheme.

### ISSUE THREAD

**Issue by jakeritz** [Zonnev/elementaryos-firefox-theme#35]
![Screenshot from 2019-10-13 13 19 26](https://user-images.githubusercontent.com/26610108/66719347-6ffd0c00-edbc-11e9-8e74-4ea659fb4b78.png)
![Screenshot from 2019-10-13 13 20 21](https://user-images.githubusercontent.com/26610108/66719348-6ffd0c00-edbc-11e9-8a7b-965ac94ac743.png)
Old CSS, vs New

**Comment by Zonnev** [comment]
Elementary os doesn't have a (default) dark theme but I know what you mean. I will work on the gradients and colours of the dark mode to fit the elementary Tweaks dark theme.

**Comment by Zonnev** [comment]
I have changed the dark mode colours but only the navigation bar and tabs bar. The rest, like the menus backgrounds, are confirm the dark mode of Firefox (which is blueish grey). I won't changed all the other elements because that would take 'forever'.

Be sure to enable Firefox dark mode, otherwise it won't work properly (like your second picture).

**Comment by jakeritz** [comment]
Wow dude, that was quick. Thanks a ton
