### ISSUE TITLE
Reduce hederbar's height when maximized (or even all the time)

### ISSUE THREAD

**Issue by ChrisP4** [Zonnev/elementaryos-firefox-theme#49]
Thanks for the awesome theme!!
 
I've noticed, elementary's apps, when maximized (or tiled-maximized vertically) have a headerbar with reduced height, as shown here:

![Captura de pantalla de 2019-12-03 21-34-18](https://user-images.githubusercontent.com/14283056/70083428-05768880-1615-11ea-9223-c73f88fe5c12.png)

Side note: Could you point me towards corrections one could make to make this permanent? I'm really thankful for the theme, and I've managed to change it as far as I have by pretty much braking and reverting as I don't know any css

**Comment by Zonnev** [comment]
Firefox does not have a sizemode state when a Firefox window is tiled in elementary os. So it's impossible to change the navigation bar's height when the window is tiled. You can change the height of the navigation bar when the window is in maximized state. The css would look something like this:

```
window[sizemode="maximized"] #nav-bar { 
    height: 40px !important; 
}
window[sizemode="maximized"] .titlebar-buttonbox { 
    top: 5px !important; 
}
window[sizemode="maximized"] #urlbar-container, #search-container { 
    padding: 3px 3px !important 
}
```
I won't put this in my userChrome because windows being tiled can not be changed by userChrome. I keep everything one size conform the size of a normal state window in elementary os.

**Comment by ChrisP4** [comment]
Thanks a lot! Managed to fix it the way I like it.

**Comment by Zonnev** [comment]
@saligari After a long time trying things out I finally fixed it today. The nav bar is responding to tiled mode! Get the latest userChrome.
