### ISSUE TITLE
[feature request] minimize button

### ISSUE THREAD

**Issue by MrFiskare** [Zonnev/elementaryos-firefox-theme#58]
Yes, I know it would not be a fully elementary-like feature, but I think it would be nice to have a minimize button at the top. Every other Mint windows has it, which makes FireFox a little bit weird to use with this theme. Other than that I really love your work so thank you!

**Comment by Zonnev** [comment]
If you delete the whole section from line 91 to 120, you will have the window control buttons **in the tab bar** any way you like it, adjustable in elementary tweaks. Since Firefox does not have the window control buttons in the navigation bar by default, its hard to adjust the navigation bar and title bar buttons for everybodies needs.

**Comment by MrFiskare** [comment]
Thank you. Yes, I totally understand. Thanks for your effort.
