### ISSUE TITLE
Bookmarks unreadable in private mode

### ISSUE THREAD

**Issue by joe247** [Zonnev/elementaryos-firefox-theme#60]
You can see _that_ from the picture here:
![Screenshot from 2020-01-20 20 14 21](https://user-images.githubusercontent.com/38415384/72735520-fdbd7400-3bc1-11ea-82c3-fe6e1534bd8b.png)

- Icons like `Show Sidebar`, `Library` & `Private` are barely visible.
- The broad bookmarks bar also looks awkward.
- I can minimize all the other elementary apps with just a right click on the title-bar (I've `set` it so from the `dconf`). If Firefox title-bar is enabled it will behave in similar manner but without it right clicking the portion near the search bar yields a context menu. Can this behaviour be changed? 
![Screenshot from 2020-01-20 21 40 10](https://user-images.githubusercontent.com/38415384/72741359-7aa21b00-3bcd-11ea-973d-a103b355fecd.png)

**Comment by Zonnev** [comment]
Hello, I've made the private mode texts better visible. I will upload the new userChrome soon.
- I wonder what is wrong with the "broad" bookmarks bar?
- Since the navigation bar is not a title bar in this theme, it won't act like a title bar. The right clicking function will not work as well because of this reason.

**Comment by Zonnev** [comment]
I have also fixed the show more bookmarks button size. Maybe that's what you were trying to explain when you wrote "The broad bookmarks bar looks awkward"?

**Comment by joe247** [comment]
>- Hello, I've made the private mode texts better visible. I will upload the new userChrome soon.

Thanks!

>- Icons like Show Sidebar, Library & Private are barely visible.

this too please.

>- I wonder what is wrong with the "broad" bookmarks bar?

Can I reduce the width of that bar (overall width)?

>- Since the navigation bar is not a title bar in this theme, it won't act like a title bar. The right clicking function will not work as well because for this reason.

Hmm... is there some other hack to minimize (other than <kbd>Super</kbd>+<kbd>H</kbd> and clicking the plank icon)?

**Comment by Zonnev** [comment]
The icon colours can not be adjusted because otherwise they wont be visible in the customize panel. For that reason I adjusted all the colours in private mode so that these icons are still visible. I will upload a new userChrome for this change. See the result:
![Schermafdruk van 2020-01-21 12 05 48](https://user-images.githubusercontent.com/32688765/72800445-acf05e80-3c47-11ea-9c68-6a6e1113206b.png)

I will not edit userChrome to adjust the width of the bookmarks bar because I like to keep it standard. You can adjust the width of the bookmark bar by adding this css to userChrome:
```
#personal-bookmarks {
  max-width: 500px !important;
}
```
You can change the 500px in something else you would like.

> Hmm... is there some other hack to minimize (other than Super+H and clicking the plank icon)?

No, unfortunately I don't know any other hack for minimizing Firefox using this theme.

**Comment by joe247** [comment]
@Zonnev thanks a lot for taking interest in this issue. Applied the new version of `userChrome.css` & now everything is readable. I'm closing this issue now.

**Comment by joe247** [comment]
Oh and one more thing the 'icon theme' does not get applied to the `close` & `maximize` buttons in private mode...

![Screenshot from 2020-01-21 18-15-17](https://user-images.githubusercontent.com/38415384/72806456-3b320800-3c7b-11ea-8ea0-9b98a1773106.png)

Also is there a way to bring the `button arrangement` like the one seen in _Telegram_?

**Comment by Zonnev** [comment]
> Oh and one more thing the 'icon theme' does not get applied to the close & maximize buttons in private mode...

This is because the theme draws them in private mode and dark mode as well. This is to make a light version of the window buttons. Note: this theme works and looks best in elementary standard GTK theme, with the standard icons applied.

> Also is there a way to bring the button arrangement like the one seen in Telegram?

This window button arrangement is different than the standard elementary arrangement. If you fiddle around with the userChrome, you could manage to make it like that but you have to make room in the navigation bar for these window buttons, so you have adjust several sections in the css file.

**Comment by joe247** [comment]
>- Since the navigation bar is not a title bar in this theme, it won't act like a title bar. The right clicking function will not work as well because for this reason.

@Zonnev I just noticed that double-clicking `navigation bar` maximizes the window... if that is possible then minimize must also be... don't you think so?

**Comment by Zonnev** [comment]
Double clicking the tab bar also maximizes Firefox, but it doesn't mean its a title bar. You won't see options for the window if you right click on the navigation bar or the tab bar. You only see this in the title bar when you activate it. It's the Firefox way of doing things, which is all baked into their code. I can not do anything about it...
