### ISSUE TITLE
White dots on the top corners while window is maximized - in another gtk theme

### ISSUE THREAD

**Issue by younyokel** [Zonnev/elementaryos-firefox-theme#61]
I have these annoying white dots on the top right and left corners of a window in maximized mode. I think they are just simply transparent:
[![Screenshot.png](https://i.postimg.cc/yxgC73C1/Screenshot.png)](https://postimg.cc/T5649wPF)

It's hard to see because the outline is white. But there is while dots and I don't know how to fix them. 

I'm using the [Elementary X by Surajmandalcell](https://github.com/surajmandalcell/elementary-x). Could this be because of it?

**Comment by Zonnev** [comment]
Seems you are not using my elementary theme for Firefox. My theme doesn't have white dots in the corners when maximized.

I guess if you maximize other windows using Elementary X, they would have the same white dots in the corners. If so, then you can blame Elementary X.

**Comment by younyokel** [comment]
> Seems you are not using my elementary theme for Firefox. My theme doesn't have white dots in the corners when maximized.
> 
> I guess if you maximize other windows using Elementary X, they would have the same white dots in the corners. If so, then you can blame Elementary X.

I would think so but it do not seems like this theme changes anything associated with windows except the close, minimize and maximize buttons. This doesn't affect on any other application. Also I tried turning off the "Title" checkbox in Firefox Preferences and it fixed the problem but some other problems appear, otherwise black (or just dark on the top) wallpapers fixes the problem.

**Comment by Zonnev** [comment]
I have figured it out somewhat: Firefox has a bug because in dark mode of elementary tweaks the title bar does not behave the same as in normal mode. In normal mode the title bar will go square when maximized. In dark mode of elementary tweaks, the title bar stays rounded when maximized and the main window of Firefox goes squared, therefore showing the white dots in the corners.
This problem can not be solved with userChrome cause the title bar and main window can not be adjusted with border radius. So the problem is not because of the GTK theme you are using.
