### ISSUE TITLE
Replace Firefox's Icon with eOS Styled Icons?

### ISSUE THREAD

**Issue by Fatih20** [Zonnev/elementaryos-firefox-theme#69]
![Screenshot from 2020-04-17 19 57 10](https://user-images.githubusercontent.com/51940383/79571761-f08f2300-80e5-11ea-9707-e009dbb7f7e8.png)
As you can see here from the screenshot, the download and sidebar icon looks out of place since they're symbolic icon that aren't even eOS styled. Is it possible that we can replace them?

**Comment by Zonnev** [comment]
When I include OS style buttons in the userChrome, the file gets impossible to work with because of the long strings that draws the icons. Code will slow down and the file gets too big. I tried it this way but didn't succeed.

The only way is to make a folder in master with the icons in it and link the CSS to those icons, asking everyone to download this folder and put it in their chrome folder. This is an inconvenient way of working so I stopped it.

So no, I'm sorry, I wont work on this matter and leave the icons of Firefox as they are.
