### ISSUE TITLE
Double-click on empty space of tabs bar cause maxmize/minimzie window

### ISSUE THREAD

**Issue by ghost** [Zonnev/elementaryos-firefox-theme#76]
When double-click on the empty space of #tabbrowser-tabs should open new tab. This is the behaviour of original firefox theme and Epiphany.

Epiphany:
![Peek 2020-05-28 09-09](https://user-images.githubusercontent.com/59665613/83087120-077b4a80-a080-11ea-9f09-b2acbb838fd1.gif)

Firefox with this theme:
![Peek 2020-05-28 09-10](https://user-images.githubusercontent.com/59665613/83087150-19f58400-a080-11ea-9685-471fb6214216.gif)

**Comment by Zonnev** [comment]
Hi, Firefox only makes new tabs by clicking the scrollwheel. Firefox is not native in elementary OS, that's why its a different method.

**Comment by binotaliu** [comment]
![Peek 2020-06-05 19-09](https://user-images.githubusercontent.com/59665613/83870151-4020c100-a71d-11ea-9fa5-33442a2bed45.gif)

Firefox with default theme (with title bar) is the same behaviour. I found that if you turns off the title bar, firefox treats the tabs bar as the title bar.
![Peek 2020-06-05 19-14](https://user-images.githubusercontent.com/59665613/83870401-bc1b0900-a71d-11ea-8e3a-6865fac18943.gif)

I don't know if it is possible to change this on the theme side, maybe by a `userChorm.js`?

**Comment by Zonnev** [comment]
I'm not good at scripts and it's a bug I can not resolve: https://bugzilla.mozilla.org/show_bug.cgi?id=1424517 

Also I really don't want another file to be downloaded and messing with Firefox internal functions which might mess up the browser. But yes, I would like double clicking to work as well because it would blend this theme into eOS even more. But on the other hand, I'm more of an button clicker and therefore I'm using the new tab button ;)
