### ISSUE TITLE
"Audio is playing" tab indicator is black instead of white.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#88]
1- Open a private window.
2- Go to Youtube and play a video.

**Result:** The audio indicator is black instead of white.

**Comment by Zonnev** [comment]
Hi, this is caused by the light mode making all icons dark, including the audio indicator. If you choose dark mode in Firefox and start a private window, the audio indicator will be bright. Making it bright by default for private mode, means that I have to put the icon code in userChrome and colour it from there, just like the navigation icons. This will be a lot a work for me, so I'm sorry but I won't work on this issue. Thanks anyway for reporting it.

**Comment by Zonnev** [comment]
Hi, I have fixed this issue, you can install the latest userChrome.
