### ISSUE TITLE
Move tab icons to the left

### ISSUE THREAD

**Issue by rootsandculture** [Zonnev/elementaryos-firefox-theme#91]
Is the an option for moving icons to the left and the close button to the right. It's very confusing.

![Screenshot from 2020-10-20 14-01-48](https://user-images.githubusercontent.com/71974607/96619738-eb9d6d00-12dc-11eb-9c83-41a35910840a.png)

**Comment by Zonnev** [comment]
Elementary OS has their close button to the left, that's why it's the same in this theme. There is no option to reverse it, unless you make your own fork of it. You can put `row` instead of `row-reverse` in line 171 in your userChrome and maybe do some tweaks with `margin-right` and `margin-left`. Good luck!
