### ISSUE TITLE
Volume icon in tab alignment off with PiP

### ISSUE THREAD

**Issue by martinstork** [Zonnev/elementaryos-firefox-theme#95]
When having media (videos) playing in a tab, the volume icon alignment is off with Picture In Picture enabled.

![Screenshot from 2020-11-19 21-35-42](https://user-images.githubusercontent.com/15929191/99721363-61991d80-2aaf-11eb-888e-73bf6aea9b83.png)

It's also using a different volume icon when PiP is enabled.

**Comment by Zonnev** [comment]
Fixed it in latest userChrome. It looks like this now:
![Schermafdruk van 2020-11-19 22 09 52](https://user-images.githubusercontent.com/32688765/99724544-0b7aa900-2ab4-11eb-8911-742c7de59679.png)

**Comment by martinstork** [comment]
Thanks! You're fast!

The different icon shown on top of the tab icon is by design (slightly different form and color)?

**Comment by Zonnev** [comment]
Yes, it's different because it's a smaller icon and still needs to be clear and sharp. I didn't design the icon, it's Firefox's own. I can put another icon in it but this icon has a link and my own icon will have a large data-string in the CSS which doesn't benefit me having to scroll past all that data. So, if I can and it doesn't look bad, I rather use Firefox's own icons ;)

**Comment by martinstork** [comment]
Thanks for the explanation. Seems logical.
