### ISSUE TITLE
Fullscreen mode (F11) doesn't show Close/Maximize window buttons.

### ISSUE THREAD

**Issue by Blast-City** [Zonnev/elementaryos-firefox-theme#97]
1- Press F11 to go to fullscreen mode.
2- Move the mouse to the top until the Firefox Ui appear.

**Result:** There is no window buttons like in Normal or Maximized mode. This doesn't seem to be happening on default Firefox.

**Comment by Zonnev** [comment]
The default Firefox window buttons in full screen change to different looking buttons, that's why I removed these buttons in full screen mode for this theme, otherwise there would be double window controls in full screen. I decided to remove them in the beginning of making this theme, so this is by design.
