### ISSUE TITLE
Allow theme to work on Firefox Nightly

### ISSUE THREAD

**Issue by gffrnl** [Zonnev/elementaryos-firefox-theme#98]
Firefox 84.0 has a bug on "Hera", a black screen behind the windows when the Title Bar is shown (in my computer has still another bug, multiple icons with low resolution shown for multiple instances of Firefox windows). 

This bug was fixed in Firefox 86.0 (currently Nightly), which I'm using ... so, until this bug is fixed in the stable version,  it would be nice to allow the scripts to change the theme of Ff Nightly too, if the user specifies it.

It seems to work if you just modify the following lines:
```
FIREFOX_DIR="${HOME}/.mozilla/firefox-trunk"
FIREFOX_DIR_FLATPAK="${HOME}/.var/app/org.mozilla.firefox/.mozilla/firefox-trunk"
```
Rather simple. It worked for me (but I haven't been able to track any side effects yet).

**Comment by Zonnev** [comment]
Thank you for suggesting a solution for the black square behind titlebar windows in Firefox but there is a reasons why I won't change the script to install the theme to Nightly:

Firefox Nightly has strange shadows under the arrow panel menu's.
![Schermafdruk van 2020-12-22 11-57-55](https://user-images.githubusercontent.com/32688765/102881761-9e10be00-444d-11eb-979d-41f53bef2b1c.png) 
_Firefox Nightly_
![Schermafdruk van 2020-12-22 11-58-04](https://user-images.githubusercontent.com/32688765/102881781-a49f3580-444d-11eb-9686-1456fd9696e0.png) 
_Firefox stable_

For this shadow problem I don't recommend to use Nightly for my theme.
The problem with the black square behind windows with a titlebar can be solved if you read here: https://github.com/Zonnev/elementaryos-firefox-theme/issues/90
The problem with multiple low resolution icon's of Firefox in Plank is probably because you installed the flatpak version of Firefox.

I hope you understand these points and will help you out solving your issues.

**Comment by gffrnl** [comment]
Humm... interesting! This problem does not occurs (on Nightly) for me ... :joy:

![Captura de tela de 2020-12-22 08-23-32](https://user-images.githubusercontent.com/67162849/102886283-97754d00-4433-11eb-8c18-d0a348d5b95f.png)

Anyway, it's just a suggestion.

I'm grateful for your reply!

I think the issue is solved.

**Comment by Zonnev** [comment]
I think you downloaded Nightly and running it from the folder. That way you don't see the strange shadow. If you install Nightly from the daily Mozilla PPA for Ubuntu, you will see this shadow. I'm afraid most people will use the PPA to keep their Nightly updated so they will see the strange shadow.

**Comment by gffrnl** [comment]
@Zonnev sorry if a closed the issue prematurely

No,no, I installed from PPA (ppa:ubuntu-mozilla-daily/ppa); its not running from the folder.
But I will follow your recommendations and fix the black frame bug in  Ff stable.

Thanks!
